#!/bin/bash
x=`sudo ls /dev/video* | tr " " "/n" | wc -l`
camera=()
table=()

for((i=1;$i <= $x;i++))
        do
        y=`sudo ls /dev/video* | tr " " "/n" | grep -m$i "video" | tail -n1`
        camera[i]=`sudo udevadm info --query=all $y | grep "ID_V4L_PRODUCT" | awk '{print substr($0,19)}'`
        done

        #echo "${camera[1]}";
        #echo "${camera[2]}";
        #echo $x;
if [ $x -eq 2 ]
then
        if [[ "${camera[1]}" == "hama C-600 Pro Webcam" && "${camera[2]}" == "Live! Cam Sync HD VF0770" ]]
        then
				echo "Settings OK"
        elif [[ "${camera[1]}" == "Live! Cam Sync HD VF0770" && "${camera[2]}" == "hama C-600 Pro Webcam" ]]
        then

				sudo mv /dev/video0 /dev/videox
				sudo mv /dev/video1 /dev/videoy
				sudo mv /dev/videox /dev/video1
				sudo mv /dev/videoy /dev/video0
				echo "Settings changed"
        fi
else
        echo "No second camera";
fi
